apiVersion: v1
kind: Service
metadata:
  name: virushack-prediction
spec:
  type: LoadBalancer
  selector:
    app: virushack-prediction
    role: virushack-prediction
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: virushack-prediction-api
  loadBalancerIP: "35.245.121.210"