apiVersion: v1
kind: Service
metadata:
  name: virushack-prediction-api
spec:
  type: LoadBalancer
  selector:
    app: virushack-prediction-api
    role: apiserver
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: prediction-admission-api
  loadBalancerIP: "35.230.173.163"
