apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: virushack-prediction
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: virushack-prediction
        role: virushack-prediction
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - main-pool
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - main-pool
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - virushack-prediction
            topologyKey: "kubernetes.io/hostname"
      containers:
        - image: gcr.io/virushack-prediction-cluster/virushack-prediction-api:staging
          imagePullPolicy: IfNotPresent
          name: api
          securityContext:
            privileged: true
          command:
          - /bin/sh
          - -c
          - >
            set -o allexport &&
            supervisord -c /etc/supervisord.conf
          ports:
            - containerPort: 80
              name: api
          env:
          - name: SLE_START_WWW
            value: "true"
          - name: SLE_RUN
            value: /var/run/sle
          - name: ENVIRONMENT
            value: staging
          - name: SLE_START_CRON
            value: "false"
          - name: MASTER_JSON
            value: /var/www/deployment/kubernetes/credentials/staging/mymed-deploy.json