version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.5
    working_directory: ~/repo
    branches:
      only:
        - develop
    steps:
      - checkout

      - run:
          name: Decrypt secrets
          command: |
            openssl aes-256-cbc -K $encrypted_po4f4nzab1o_key -iv $encrypted_po4f4nzab1o_iv -in deployment/kubernetes/credentials.zip.enc -out deployment/kubernetes/credentials.zip -d
            unzip deployment/kubernetes/credentials.zip -d deployment/kubernetes

      - run:
          name: Temporary prepare circleci image
          command: |
            sudo apt-get update &&
            sudo apt-get install -y lsb-release &&
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" &&
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list &&
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - &&
            sudo apt-get update &&
            sudo apt-get install -y google-cloud-sdk kubectl

      - setup_remote_docker:
          reusable: true
          exclusive: true


      - run:
          name: Run build
          command: |
            chmod +x deployment/scripts/circle-ci/build.sh && deployment/scripts/circle-ci/build.sh

      - run:
          name: Push application Docker image
          command: |
            chmod +x deployment/scripts/circle-ci/push.sh && deployment/scripts/circle-ci/push.sh

      - deploy:
          name: Run deploy
          command: |
            chmod +x deployment/scripts/circle-ci/deploy.sh && deployment/scripts/circle-ci/deploy.sh
